name: Generate snake game

on:
  schedule:
    - cron: "* */12 * * *"  # Every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Generate SVG Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake SVG
        uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'  # Change to 'green', 'pink', etc. if you want

      - name: Deploy SVG to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
